### ISSUE TITLE
Establish data flow through Home Page

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#118]
## What's the desired result?

`/`, the index page is connected to the CMS and pulling in data correctly.

## Tasks
- [x] Pass data from CMS query as props to `<HomeMixes />`
- [x] Pass data from CMS query as props to `<HomeFeatures />`
- [ ] Pass data from CMS query as props to `<HomeEvents />`

## Related issues

#80, #83

**Comment by chrismejia** [comment]
Missed commit.
