### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#147]
# THINGS TO DO BEFORE LAUNCH

- [x] Set up Github: [HalfmoonBK Organization](https://github.com/half-moon-bk)
- [x] Set up Netlify: [Halfmoonbk's team](https://app.netlify.com/teams/halfmoonbk/overview)
- [x] Transfer Prismic repo
- [x] Duplicate Firebase project
- [x] Lock down Firebase project
- [x] Integrate HMBK Shop link to navbar
- [x] New Google Maps Embed API key (whitelist halfmoonbk.com only)
- [x] Transfer domain ownership (google domains)
- [x] #27 - Convert **Live** test button

**Comment by chrismejia** [comment]
# NOTE: THE KITCHEN SINK FEATURE IS NOT TO BE DELETED

## Dev Entries
## Saved to repo as JSON, then deleted

- `EventTemplate.json`: 25th Anniversary Purple People Eaters' Reunion Carnival Extravaganzathon!
- `ResidentTemplate.json`: KOAN Sound
- `TheKitchenSink.json`: The Kitchen Sink Article

## Deleted from CMS

### Residents
- DJ Slavine
- Infected Mushroom (DJ Freedem – 10.05.20 mix)
- Thank You Scientist

### Mixes
- Russian Hard Bass 2019 LIVE Mix (Slavine)
- More Than Just a Name (Thank You Scientist, KOAN Sound, Infected Mushroom)
- Terraformer (Thank You Scientist)
- Dev Moon Album (TYS, IM)
- Call of Ktulu (IM)
- Letargo (TYS)
- Circadia (TYS)
- Abis - If U
- Taken Under ft. Anna Lisa
- Grounded ft. Javeon
- Cosmic Tuba
- Silk Wave
- Silk Wave (EP)

### Editorials
- Short Feature Title
- Denali Fest 2025: The Alaska Mountaintop Frozen Festival We Didn't Know We Needed

### Collections
- Silk Wave

**Comment by chrismejia** [comment]
All tasks on checklist complete; site is live.
