### ISSUE TITLE
Renovate current mixes page 

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#78]
## What's the desired result?

`/mixes` has a basic page layout for mixes page.

## Tasks

- [x] Rewrite existing `/pages/mixes/index.js`
  - [x] Add titling
  - [x] Add placeholder space for search fields
  - [x] Search bar
  - [x] Tag selection
  - [x] Add dummy mix list from HomeMixes/BioMixList to this page
- [x] Delete the following pages and refs in `src/components/index` - 789786d
  - [x] In `/pages`: `daily-mixes`
  - [x] In `/components`: `MixesPage`, `MixesPageMix`, `SingleMix`
- [x] Add working `/mixes` link to BottomNav; see #47 

## Related issues

#47, #79, #80
