### ISSUE TITLE
Establish data flow through /search page

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#83]
## What's the desired result?

`/search` page is connected to the CMS and pulling in data correctly.

## Inspiration

https://www.dublab.com/search/beats?type=broadcasts

## Tasks

- [ ] When a search is started, the appropriate categories with search results populate
  - [ ] The number of search results for that category appears adjacent to the search category title
- [ ] A default category (column) is selected and the page populates those results into the page
  - [ ] If there are a large number of search results, lazy load anything past the first X results

## Related issues

#82

**Comment by chrismejia** [comment]
Search will be implemented in another contract.
