### ISSUE TITLE
Pass artist to globalState from SingleMixCard

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#85]
## What's the current behavior?

The artist for the current show/mix only displays on initial page load, when the TopNav is in *NOT LIVE* layout.

## What's the desired behavior?

The artist for the current show/mix only displays on all layouts, whether or not it's the live stream that's playing or a different mix.

## Tasks

**NOT LIVE**
- [x] Static Tablet-up text
- [ ] Dynamic Mobile Ticker text

**LIVE**
- [ ] Static Tablet-up text
- [ ] Dynamic Mobile Ticker text 

## Related Issues

#35 - @richdacuban already added `artist` to `globalState` and `CHANGE_URL` reducer action
#53 -  Make sure to format the result in a way that closes this issue
#66 - Now that it's closed, we can make this change once to reflect everywhere
