### ISSUE TITLE
Thin existing border weights and change to white

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#93]
## Tasks

- [x] Change card border widths
- [x] Change home page divider width
- [x] Change schedule border width and type
- [x] Change TopNav bottom border width and color
- [x] Change BottomNav top border width and color

**Comment by chrismejia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Next Steps 4.24](https://trello.com/c/GKLKlXeY/94-next-steps-424)
