### ISSUE TITLE
Make home events and news use SingleMixCard

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#98]
## Tasks

- [ ] Make HomeEvents use SingleMixCard
- [ ] Make HomeNews use SingleMixCard
- [ ] Rename SingleMixCard to SingleItemCard
